name: CI Basic Information Workflow  # 1. Dale un nombre descriptivo a tu workflow

on:
  push: # 2. ¿Qué evento(s) quieres usar para disparar este workflow? (añade mínimo 2)
        #    Piensa en cuándo quieres que se ejecute (push, pull_request, manualmente...).
    branches: # 2b. (Opcional) ¿Quieres restringirlo a alguna rama específica?
      - main
  workflow_dispatch: # Añadido segundo evento para permitir ejecución manual

jobs:
  imprimir_info:  # No cambies este nombre, lo usaremos para evaluar
    runs-on: ubuntu-latest  # 3. ¿En qué sistema operativo quieres que se ejecute este job?

    steps:
      - uses: actions/checkout@v3  # Este paso clona tu repositorio. No lo modifiques.

      - name: Imprimir Mensaje Personalizado
        # 4. Reemplaza [TU NOMBRE COMPLETO] con tu nombre.
        # 5. ¿Qué comando de shell usarías para obtener la fecha y hora?
        run: |
          echo "Hola, soy Antonio Carmona y este es mi primer workflow!"  
          echo "La fecha y hora actual es: $(date)"  

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' # 6. Elige una versión de Python

      - name: Ejecutar script Python
        run: python mi_script.py #7. Completa para ejecutar el script de python